package com.annaru.upms.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2019-05-17T18:53:41.520+08:00
 * Generated source version: 3.2.3
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "LisWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface LisWebServiceSoap {

    /**
     * 数据接口方法:WEBCMD表示命令字（HelloWorld,Login,CMLUpLoadApp,GetResultLists,DownLoadResult,UpdateSatus），Params为XML格式的输入参数
     */
    @WebMethod(operationName = "CMLDataTrans", action = "http://tempuri.org/CMLDataTrans")
    @RequestWrapper(localName = "CMLDataTrans", targetNamespace = "http://tempuri.org/", className = "com.annaru.CMLDataTrans")
    @ResponseWrapper(localName = "CMLDataTransResponse", targetNamespace = "http://tempuri.org/", className = "com.annaru.CMLDataTransResponse")
    @WebResult(name = "CMLDataTransResult", targetNamespace = "http://tempuri.org/")
    public String cmlDataTrans(
            @WebParam(name = "WEBCMD", targetNamespace = "http://tempuri.org/") String webcmd,
            @WebParam(name = "Params", targetNamespace = "http://tempuri.org/") String params);
}
