
package com.annaru.upms.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.net.URL;
import java.util.Map;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2019-05-17T18:53:41.514+08:00
 * Generated source version: 3.2.3
 */
public final class LisWebServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "LisWebService");


    public static Map<String, Object> sendRequest(String _cmlDataTrans_webcmd, Map<String, String> reqData) throws Exception {
        URL wsdlURL = LisWebService.WSDL_LOCATION;
        LisWebService lisWebService = new LisWebService(wsdlURL, SERVICE_NAME);
        LisWebServiceSoap port = lisWebService.getLisWebServiceSoap();

        String _cmlDataTrans_params = WebServiceXmlUtil.mapToXml(reqData);

        System.out.println("Invoking cmlDataTrans...");
        String _cmlDataTrans__return = port.cmlDataTrans(_cmlDataTrans_webcmd, _cmlDataTrans_params);
        System.out.println("cmlDataTrans.result=" + _cmlDataTrans__return);

        Map<String, Object> resData = WebServiceXmlUtil.xmlToMap(_cmlDataTrans__return);

        return resData;
    }

}
