
package com.annaru.upms.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.net.URL;
import java.util.Map;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2019-05-17T18:53:41.483+08:00
 * Generated source version: 3.2.3
 */
public final class LisWebServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "LisWebService");

    public static Map<String, Object> sendRequest(String _cmlDataTrans_webcmd, Map<String, String> reqData) throws Exception {
        /**
         * @Description:
         * @param cmlDataTrans_webcmd 接口命令字(服务名称)
         * @param reqData 输入参数
         * @Author: XCK
         * @Date: 2019/5/20
         * @return Map<String, Object>
         */
        URL wsdlURL = LisWebService.WSDL_LOCATION;
        LisWebService lisWebService = new LisWebService(wsdlURL, SERVICE_NAME);
        LisWebServiceSoap port = lisWebService.getLisWebServiceSoap12();
        String _cmlDataTrans_params = WebServiceXmlUtil.mapToXml(reqData);

        System.out.println("Invoking cmlDataTrans...");
        String _cmlDataTrans__return = port.cmlDataTrans(_cmlDataTrans_webcmd, _cmlDataTrans_params);
        System.out.println("cmlDataTrans.result=" + _cmlDataTrans__return);

        Map<String, Object> resData = WebServiceXmlUtil.xmlToMap(_cmlDataTrans__return);

        return resData;
    }

}
