package com.annaru.upms.entity.medical;

import com.baomidou.mybatisplus.extension.activerecord.Model;

import java.io.Serializable;
import java.util.Date;

/**
 * 表名：tb_yl_zy_medical_record(住院就诊记录表) 
 * Generated by 上海格欣信息技术有限公司  
 */
@SuppressWarnings("serial")
public abstract class TbYlZyMedicalRecord extends Model<TbYlZyMedicalRecord> implements Serializable {
	private static final long serialVersionUID = 1L;

	/** 住院就诊记录表ID*/
	private String csid;
	/** 医疗机构代码*/
	private String yljgdm;
	/** 住院就诊流水号*/
	private String jzlsh;
	/** 住院号*/
	private String cisid;
	/** 病案号*/
	private String bah;
	/** 卡号*/
	private String kh;
	/** 卡类型*/
	private String klx;
	/** 患者姓名*/
	private String hzxm;
	/** 就诊类型*/
	private String jzlx;
	/** 入院科室编码*/
	private String jzksbm;
	/** 入院科室名称*/
	private String jzksmc;
	/** 出院科室编码*/
	private String cyksbm;
	/** 出院科室名称*/
	private String cyksmc;
	/** 入院时间*/
	private String rysj;
	/** 出院时间*/
	private String cysj;
	/** 修改标志*/
	private String xgbz;
	/** 修改日期*/
	private Date updateTime;

	public String getCsid() {
		return csid;
	}

	public void setCsid(String csid) {
		this.csid = csid;
	}

	public String getYljgdm() {
		return yljgdm;
	}

	public void setYljgdm(String yljgdm) {
		this.yljgdm = yljgdm;
	}

	public String getJzlsh() {
		return jzlsh;
	}

	public void setJzlsh(String jzlsh) {
		this.jzlsh = jzlsh;
	}

	public String getCisid() {
		return cisid;
	}

	public void setCisid(String cisid) {
		this.cisid = cisid;
	}

	public String getBah() {
		return bah;
	}

	public void setBah(String bah) {
		this.bah = bah;
	}

	public String getKh() {
		return kh;
	}

	public void setKh(String kh) {
		this.kh = kh;
	}

	public String getKlx() {
		return klx;
	}

	public void setKlx(String klx) {
		this.klx = klx;
	}

	public String getHzxm() {
		return hzxm;
	}

	public void setHzxm(String hzxm) {
		this.hzxm = hzxm;
	}

	public String getJzlx() {
		return jzlx;
	}

	public void setJzlx(String jzlx) {
		this.jzlx = jzlx;
	}

	public String getJzksbm() {
		return jzksbm;
	}

	public void setJzksbm(String jzksbm) {
		this.jzksbm = jzksbm;
	}

	public String getJzksmc() {
		return jzksmc;
	}

	public void setJzksmc(String jzksmc) {
		this.jzksmc = jzksmc;
	}

	public String getCyksbm() {
		return cyksbm;
	}

	public void setCyksbm(String cyksbm) {
		this.cyksbm = cyksbm;
	}

	public String getCyksmc() {
		return cyksmc;
	}

	public void setCyksmc(String cyksmc) {
		this.cyksmc = cyksmc;
	}

	public String getRysj() {
		return rysj;
	}

	public void setRysj(String rysj) {
		this.rysj = rysj;
	}

	public String getCysj() {
		return cysj;
	}

	public void setCysj(String cysj) {
		this.cysj = cysj;
	}

	public String getXgbz() {
		return xgbz;
	}

	public void setXgbz(String xgbz) {
		this.xgbz = xgbz;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}
